using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aspire.Hosting.AspireC4.SourceGenerators;

/// <summary>Generates <c>KnownLikeC4Elements</c> from tagged registry classes.</summary>
[Generator]
public sealed class KnownLikeC4ElementsGenerator : IIncrementalGenerator
{
	const string TagRegistryAttributeMetadataName =
		"Aspire.Hosting.AspireC4.LikeC4.Models.KnownLikeC4TagRegistryAttribute";
	const string ElementKindRegistryAttributeMetadataName =
		"Aspire.Hosting.AspireC4.LikeC4.Models.KnownLikeC4ElementKindRegistryAttribute";

	static readonly char[] NameSeparators = new[] { '_', '-' };

	const string AttributeSource = """
// <auto-generated />
// Generated by AspireC4.SourceGenerators — do not edit manually.
#nullable enable

namespace Aspire.Hosting.AspireC4.LikeC4.Models;

/// <summary>
/// Marks a static class as a source of known LikeC4 state tags.
/// All public const string fields are collected by KnownLikeC4ElementsGenerator
/// and included in KnownLikeC4Elements.Tags. Field names are converted to PascalCase.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class KnownLikeC4TagRegistryAttribute : global::System.Attribute { }

/// <summary>
/// Marks a static class as a source of known LikeC4 element kinds.
/// All public const string fields are collected by KnownLikeC4ElementsGenerator
/// and included in KnownLikeC4Elements.ElementKinds. Field names are converted to PascalCase.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class KnownLikeC4ElementKindRegistryAttribute : global::System.Attribute { }
""";

	/// <summary>Initializes the generator pipeline.</summary>
	/// <param name="context">The incremental generator initialization context.</param>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static postInitializationContext =>
			postInitializationContext.AddSource(
				"KnownLikeC4Attributes.g.cs",
				SourceText.From(AttributeSource, Encoding.UTF8)
			)
		);

		var tagFields = CreateRegistryFieldProvider(context, TagRegistryAttributeMetadataName).Collect();
		var elementKindFields = CreateRegistryFieldProvider(context, ElementKindRegistryAttributeMetadataName)
			.Collect();

		context.RegisterSourceOutput(
			tagFields.Combine(elementKindFields),
			static (productionContext, source) =>
			{
				var (tags, elementKinds) = source;
				EmitKnownLikeC4Elements(productionContext, tags, elementKinds);
			}
		);
	}

	/// <summary>Converts a dash/underscore separated name into PascalCase.</summary>
	/// <param name="name">The name to convert.</param>
	/// <returns>The PascalCase representation of <paramref name="name" />.</returns>
	internal static string ToPascalCase(string name)
	{
		if (string.IsNullOrEmpty(name))
		{
			return string.Empty;
		}

		var segments = name.Split(NameSeparators, StringSplitOptions.RemoveEmptyEntries);
		if (segments.Length == 0)
		{
			return string.Empty;
		}

		StringBuilder builder = new(name.Length);
		foreach (var segment in segments)
		{
			if (segment.Length == 0)
			{
				continue;
			}

			builder.Append(char.ToUpperInvariant(segment[0]));
			builder.Append(segment.Length == 1 ? string.Empty : NormalizeSegmentTail(segment));
		}

		return builder.ToString();
	}

	static IncrementalValuesProvider<KnownLikeC4Field> CreateRegistryFieldProvider(
		IncrementalGeneratorInitializationContext context,
		string attributeMetadataName
	)
	{
		return context
			.SyntaxProvider.ForAttributeWithMetadataName(
				attributeMetadataName,
				static (node, _) => node is ClassDeclarationSyntax,
				static (generatorContext, _) => GetFields(generatorContext)
			)
			.SelectMany(static (fields, _) => fields);
	}

	static ImmutableArray<KnownLikeC4Field> GetFields(GeneratorAttributeSyntaxContext context)
	{
		if (context.TargetSymbol is not INamedTypeSymbol { IsStatic: true } typeSymbol)
		{
			return ImmutableArray<KnownLikeC4Field>.Empty;
		}

		return typeSymbol
			.GetMembers()
			.OfType<IFieldSymbol>()
			.Where(static field =>
				field
					is {
						IsConst: true,
						DeclaredAccessibility: Accessibility.Public,
						Type.SpecialType: SpecialType.System_String,
					}
			)
			.Select(field => new KnownLikeC4Field(
				ToPascalCase(field.Name),
				field.ConstantValue as string ?? string.Empty,
				typeSymbol.ToDisplayString()
			))
			.ToImmutableArray();
	}

	static void EmitKnownLikeC4Elements(
		SourceProductionContext context,
		ImmutableArray<KnownLikeC4Field> tagFields,
		ImmutableArray<KnownLikeC4Field> elementKindFields
	)
	{
		var normalizedTags = NormalizeFields(tagFields);
		var normalizedElementKinds = NormalizeFields(elementKindFields);
		if (normalizedTags.IsEmpty && normalizedElementKinds.IsEmpty)
		{
			return;
		}

		StringBuilder builder = new();
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine("// Generated by AspireC4.SourceGenerators — do not edit manually.");
		builder.AppendLine();
		builder.AppendLine("#nullable enable");
		builder.AppendLine("#pragma warning disable CS1591");
		builder.AppendLine();
		builder.AppendLine("namespace Aspire.Hosting.AspireC4.LikeC4.Models;");
		builder.AppendLine();
		builder.AppendLine(
			"/// <summary>Contains all known LikeC4 element types generated from registry classes.</summary>"
		);
		builder.AppendLine("public static partial class KnownLikeC4Elements");
		builder.AppendLine("{");
		AppendNestedClass(builder, "Tags", "Known state tags for Aspire resource run states.", normalizedTags);
		builder.AppendLine();
		AppendNestedClass(builder, "ElementKinds", "Known LikeC4 element kinds.", normalizedElementKinds);
		builder.AppendLine("}");
		builder.AppendLine();
		builder.AppendLine("#pragma warning restore CS1591");

		context.AddSource("KnownLikeC4Elements.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
	}

	static ImmutableArray<KnownLikeC4Field> NormalizeFields(ImmutableArray<KnownLikeC4Field> fields)
	{
		return fields
			.Where(static field => !string.IsNullOrWhiteSpace(field.Name))
			.GroupBy(static field => field.Name, StringComparer.Ordinal)
			.Select(static group =>
				group
					.OrderBy(static field => field.RegistryTypeName, StringComparer.Ordinal)
					.ThenBy(static field => field.Value, StringComparer.Ordinal)
					.First()
			)
			.OrderBy(static field => field.Name, StringComparer.Ordinal)
			.ToImmutableArray();
	}

	static void AppendNestedClass(
		StringBuilder builder,
		string className,
		string summary,
		ImmutableArray<KnownLikeC4Field> fields
	)
	{
		builder.Append("\t/// <summary>").Append(summary).AppendLine("</summary>");
		builder.Append("\tpublic static class ").Append(className).AppendLine();
		builder.AppendLine("\t{");

		foreach (var field in fields)
		{
			builder
				.Append("\t\tpublic const string ")
				.Append(field.Name)
				.Append(" = ")
				.Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(field.Value, true))
				.AppendLine(";");
		}

		builder.AppendLine("\t}");
	}

	static string NormalizeSegmentTail(string segment)
	{
		var tail = segment.Substring(1);
		return segment.All(static character => !char.IsLetter(character) || char.IsUpper(character))
			? new string(tail.Select(static character => char.ToLowerInvariant(character)).ToArray())
			: tail;
	}

	readonly struct KnownLikeC4Field
	{
		public KnownLikeC4Field(string name, string value, string registryTypeName)
		{
			Name = name;
			Value = value;
			RegistryTypeName = registryTypeName;
		}

		public string Name { get; }

		public string Value { get; }

		public string RegistryTypeName { get; }
	}
}
