using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aspire.Hosting.AspireC4.SourceGenerators;

/// <summary>
/// Generates <c>KnownLikeC4Registry</c> by discovering string values passed to
/// <c>.WithTag()</c> and <c>.WithKind()</c> call sites, including via <c>const</c> references.
/// </summary>
[Generator]
public sealed class KnownLikeC4RegistryGenerator : IIncrementalGenerator
{
	static readonly char[] NameSeparators = ['_', '-'];

	const string WithTagMethodName = "WithTag";
	const string WithKindMethodName = "WithKind";
	const string WithGroupMethodName = "WithLikeC4Group";

	/// <summary>Initializes the incremental generator pipeline.</summary>
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var tagValues = CreateStringArgProvider(context, WithTagMethodName).Collect();
		var kindValues = CreateStringArgProvider(context, WithKindMethodName).Collect();
		var groupValues = CreateStringArgProvider(context, WithGroupMethodName).Collect();

		context.RegisterSourceOutput(
			tagValues.Combine(kindValues).Combine(groupValues),
			static (ctx, source) => EmitRegistry(ctx, source.Left.Left, source.Left.Right, source.Right)
		);
	}

	/// <summary>Converts a dash/underscore-separated name into PascalCase.</summary>
	/// <remarks>
	/// Any character that is not a letter, digit, hyphen, or underscore is treated as a
	/// word separator (replaced with a hyphen) before splitting. This allows group names
	/// such as "Local Dev/ Sync Group" to be safely converted to "LocalDevSyncGroup".
	/// </remarks>
	internal static string ToPascalCase(string name)
	{
		if (string.IsNullOrEmpty(name))
			return string.Empty;

		// Normalize non-separator, non-alnum characters to hyphens so they act as word boundaries.
		var sanitized = new string(
			name.Select(static c => char.IsLetterOrDigit(c) || c == '-' || c == '_' ? c : '-').ToArray()
		);

		var segments = sanitized.Split(NameSeparators, StringSplitOptions.RemoveEmptyEntries);
		if (segments.Length == 0)
			return string.Empty;

		StringBuilder sb = new(name.Length);
		foreach (var segment in segments)
		{
			if (segment.Length == 0)
				continue;

			sb.Append(char.ToUpperInvariant(segment[0]));
			if (segment.Length > 1)
				sb.Append(NormalizeSegmentTail(segment));
		}

		return sb.ToString();
	}

	static IncrementalValuesProvider<string> CreateStringArgProvider(
		IncrementalGeneratorInitializationContext context,
		string methodName
	)
	{
		return context
			.SyntaxProvider.CreateSyntaxProvider(
				predicate: (node, _) => IsTargetInvocation(node, methodName),
				transform: (ctx, ct) => ExtractConstStringArg(ctx, ct)
			)
			.Where(static v => v is not null)
			.Select(static (v, _) => v!);
	}

	static bool IsTargetInvocation(SyntaxNode node, string methodName)
	{
		return node
				is InvocationExpressionSyntax
				{
					ArgumentList.Arguments.Count: > 0,
					Expression: MemberAccessExpressionSyntax { Name.Identifier.Text: var name },
				}
			&& name == methodName;
	}

	static string? ExtractConstStringArg(GeneratorSyntaxContext ctx, CancellationToken ct)
	{
		var invocation = (InvocationExpressionSyntax)ctx.Node;
		var firstArg = invocation.ArgumentList.Arguments[0].Expression;
		var constant = ctx.SemanticModel.GetConstantValue(firstArg, ct);

		return constant.HasValue && constant.Value is string value ? value : null;
	}

	static void EmitRegistry(
		SourceProductionContext context,
		ImmutableArray<string> tagValues,
		ImmutableArray<string> kindValues,
		ImmutableArray<string> groupValues
	)
	{
		var tags = NormalizeToFields(tagValues);
		var kinds = NormalizeToFields(kindValues);
		var groups = NormalizeToFields(groupValues);

		if (tags.IsEmpty && kinds.IsEmpty && groups.IsEmpty)
			return;

		StringBuilder sb = new();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("// Generated by AspireC4.SourceGenerators — do not edit manually.");
		sb.AppendLine();
		sb.AppendLine("#nullable enable");
		sb.AppendLine("#pragma warning disable CS1591");
		sb.AppendLine();
		sb.AppendLine("namespace Aspire.Hosting.AspireC4.LikeC4.Models;");
		sb.AppendLine();
		sb.AppendLine(
			"/// <summary>Contains all known LikeC4 registry values discovered from call-site usages.</summary>"
		);
		sb.AppendLine("public static partial class KnownLikeC4Registry");
		sb.AppendLine("{");
		AppendNestedClass(sb, "Tags", "Known tags discovered from .WithTag(...) call sites.", tags);
		sb.AppendLine();
		AppendNestedClass(sb, "ElementKinds", "Known element kinds discovered from .WithKind(...) call sites.", kinds);
		sb.AppendLine();
		AppendNestedClass(sb, "Groups", "Known group names discovered from .WithLikeC4Group(...) call sites.", groups);
		sb.AppendLine("}");
		sb.AppendLine();
		sb.AppendLine("#pragma warning restore CS1591");

		context.AddSource("KnownLikeC4Registry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
	}

	static ImmutableArray<KnownField> NormalizeToFields(ImmutableArray<string> values)
	{
		return values
			.Where(static v => !string.IsNullOrWhiteSpace(v))
			.Distinct(StringComparer.Ordinal)
			.Select(static v => new KnownField(ToPascalCase(v), v))
			.Where(static f => !string.IsNullOrEmpty(f.Name))
			.OrderBy(static f => f.Name, StringComparer.Ordinal)
			.ToImmutableArray();
	}

	static void AppendNestedClass(StringBuilder sb, string className, string summary, ImmutableArray<KnownField> fields)
	{
		sb.Append("\t/// <summary>").Append(summary).AppendLine("</summary>");
		sb.Append("\tpublic static class ").AppendLine(className);
		sb.AppendLine("\t{");

		foreach (var field in fields)
		{
			sb.Append("\t\tpublic const string ")
				.Append(field.Name)
				.Append(" = ")
				.Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(field.Value, true))
				.AppendLine(";");
		}

		sb.AppendLine("\t}");
	}

	static string NormalizeSegmentTail(string segment)
	{
		var tail = segment.Substring(1);
		return segment.All(static c => !char.IsLetter(c) || char.IsUpper(c))
			? new string([.. tail.Select(static c => char.ToLowerInvariant(c))])
			: tail;
	}

	readonly struct KnownField(string name, string value)
	{
		public string Name { get; } = name;

		public string Value { get; } = value;
	}
}
